name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build
      run: dotnet build ./src/ConveyContrib.WebApi.MediatR.sln --configuration Release
    - name: Test
      run: dotnet test ./ConveyContrib.WebApi.MediatR.Tests/ConveyContrib.WebApi.MediatR.Tests.csproj --no-restore --no-build 
    - name: Package
      run: dotnet pack ./src/ConveyContrib.WebApi.MediatR/ConveyContrib.WebApi.MediatR.csproj --configuration Release --no-restore --no-build
