name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Version
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.github_token}}        
    - name: Print new build number
      run: echo "Build number is $BUILD_NUMBER"
    - name: Build
      run: dotnet build ./src/ConveyContrib.WebApi.MediatR.sln --configuration Release -p:Version=1.0.$BUILD_NUMBER
    - name: Test
      run: dotnet test ./src/ConveyContrib.WebApi.MediatR.sln --configuration Release
    - name: Package
      run: dotnet pack ./src/ConveyContrib.WebApi.MediatR/ConveyContrib.WebApi.MediatR.csproj --configuration Release --no-restore --no-build -p:PackageVersion=1.0.$BUILD_NUMBER
